In [1]:
# 載入需要的套件
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns # 另一個繪圖-樣式套件

# 忽略警告訊息
%matplotlib inline
plt.style.use('ggplot')
import warnings
warnings.filterwarnings('ignore')

# 設定 data_path
dir_data = './data/'

In [2]:
f_app1 = os.path.join(dir_data, 'train.csv')
print('Path of read in data: %s' % (f_app1))
train = pd.read_csv(f_app1, header = None)
print(len(train))
train.head()

# train = pd.read_csv('train.csv', header=None)
# trainLabel = pd.read_csv('../data/trainLabels.csv', header=None)
# test = pd.read_csv('../data/test.csv', header=None)

Path of read in data: ./data/train.csv
1000

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0.299403,-1.226624,1.498425,-1.176150,5.289853,0.208297,2.404498,1.594506,-0.051608,0.663234,...,-0.850465,-0.622990,-1.833057,0.293024,3.552681,0.717611,3.305972,-2.715559,-2.682409,0.101050
1,-1.174176,0.332157,0.949919,-1.285328,2.199061,-0.151268,-0.427039,2.619246,-0.765884,-0.093780,...,-0.819750,0.012037,2.038836,0.468579,-0.517657,0.422326,0.803699,1.213219,1.382932,-1.817761
2,1.192222,-0.414371,0.067054,-2.233568,3.658881,0.089007,0.203439,-4.219054,-1.184919,-1.240310,...,-0.604501,0.750054,-3.360521,0.856988,-2.751451,-1.582735,1.672246,0.656438,-0.932473,2.987436
3,1.573270,-0.580318,-0.866332,-0.603812,3.125716,0.870321,-0.161992,4.499666,1.038741,-1.092716,...,1.022959,1.275598,-3.480110,-1.065252,2.153133,1.563539,2.767117,0.215748,0.619645,1.883397
4,-0.613071,-0.644204,1.112558,-0.032397,3.490142,-0.011935,1.443521,-4.290282,-1.761308,0.807652,...,0.513906,-1.803473,0.518579,-0.205029,-4.744566,-1.520015,1.830651,0.870772,-1.894609,0.408332

In [3]:
f_app2 = os.path.join(dir_data, 'trainLabels.csv')
print('Path of read in data: %s' % (f_app2))
trainLabels = pd.read_csv(f_app2, header = None)
print(len(trainLabels))
trainLabels.head()

Path of read in data: ./data/trainLabels.csv
1000

   0
0  1
1  0
2  0
3  1
4  0

In [4]:
f_app3 = os.path.join(dir_data, 'test.csv')
print('Path of read in data: %s' % (f_app3))
test = pd.read_csv(f_app3, header = None)
test.head()

Path of read in data: ./data/test.csv

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2.808909,-0.242894,-0.546421,0.255162,1.749736,-0.030458,-1.322071,3.578071,-0.667578,-0.884257,...,-0.261688,-0.224375,-1.675606,-0.479584,-0.244388,-0.672355,0.517860,0.010665,-0.419214,2.818387
1,-0.374101,0.537669,0.081063,0.756773,0.915231,2.557282,3.703187,1.673835,-0.764122,-1.228040,...,-0.969463,0.574154,-2.200519,-1.612240,0.179031,-2.924596,0.643610,-1.470939,-0.067408,-0.976265
2,-0.088370,0.154743,0.380716,-1.176126,1.699867,-0.258627,-1.384999,1.093584,1.596633,0.230631,...,-0.769885,-0.005143,1.467490,0.483803,-3.542981,0.814561,-1.652948,1.265866,-1.749248,1.773784
3,-0.685635,0.501283,1.873375,0.215224,-3.983468,-0.103637,4.136113,-0.225431,-1.515015,-1.071763,...,0.968609,2.386412,-0.131219,0.285646,2.302069,1.255588,-1.563090,-0.125258,-1.030761,-2.945329
4,0.350867,0.721897,-0.477104,-1.748776,-2.627405,1.075433,4.954253,-3.293501,-0.760369,0.204360,...,0.260553,-2.045650,-2.173227,0.372992,0.450700,-0.211657,1.301359,-0.522164,2.484883,0.039213

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
0     1000 non-null float64
1     1000 non-null float64
2     1000 non-null float64
3     1000 non-null float64
4     1000 non-null float64
5     1000 non-null float64
6     1000 non-null float64
7     1000 non-null float64
8     1000 non-null float64
9     1000 non-null float64
10    1000 non-null float64
11    1000 non-null float64
12    1000 non-null float64
13    1000 non-null float64
14    1000 non-null float64
15    1000 non-null float64
16    1000 non-null float64
17    1000 non-null float64
18    1000 non-null float64
19    1000 non-null float64
20    1000 non-null float64
21    1000 non-null float64
22    1000 non-null float64
23    1000 non-null float64
24    1000 non-null float64
25    1000 non-null float64
26    1000 non-null float64
27    1000 non-null float64
28    1000 non-null float64
29    1000 non-null float64
30    1000 non-null float64
31    1000 non-null float64
32    1000 non-null float64
33    1000 non-null float64
34    1000 non-null float64
35    1000 non-null float64
36    1000 non-null float64
37    1000 non-null float64
38    1000 non-null float64
39    1000 non-null float64
dtypes: float64(40)
memory usage: 312.6 KB

In [6]:
train.describe()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.025596,-0.024526,-0.024088,-0.002271,1.092329,-0.006250,0.497342,-0.037883,0.026391,-0.003597,...,0.030651,0.022951,-0.542491,-0.011608,-0.483507,0.033371,0.567185,0.006849,-0.892659,0.609451
std,1.008282,1.016298,0.979109,0.970575,4.538834,0.989128,2.118819,2.232256,1.001064,1.013520,...,1.011645,1.001375,2.239939,1.022456,2.121281,1.007044,2.227876,0.997635,2.022022,2.045439
min,-3.365711,-3.492086,-2.695602,-3.460471,-16.421901,-3.041250,-7.224761,-6.509084,-3.145588,-2.749812,...,-3.379194,-2.971125,-7.840890,-2.999564,-7.124105,-2.952358,-5.452254,-3.473913,-8.051722,-7.799086
25%,-0.669010,-0.693937,-0.698830,-0.617557,-1.801997,-0.732265,-0.838619,-1.604037,-0.677562,-0.682220,...,-0.659457,-0.696032,-2.121943,-0.664550,-1.879247,-0.642861,-1.059786,-0.691162,-2.220126,-0.565041
50%,0.027895,-0.033194,0.008145,0.002327,0.862818,0.027041,0.582321,0.018809,0.022092,-0.036110,...,0.049416,0.049778,-0.568262,-0.028097,-0.493575,0.037732,0.455474,0.038284,-0.855470,0.779944
75%,0.762520,0.682753,0.661434,0.640743,3.843172,0.671456,1.913664,1.438304,0.741310,0.665364,...,0.747031,0.699917,0.939348,0.651374,1.005795,0.691800,2.122157,0.693535,0.388698,1.992193
max,3.326246,3.583870,2.546507,3.088738,17.565345,3.102997,7.592666,7.130097,3.145258,3.919426,...,2.844792,3.688047,7.160379,3.353631,6.005818,3.420561,6.603499,3.492548,5.774120,6.803984

In [7]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [8]:
x_train,x_test,y_train,y_test = train_test_split(train, trainLabels, test_size = 0.30, random_state = 1)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((700, 40), (300, 40), (700, 1), (300, 1))

In [9]:
# 建立模型

reg = GradientBoostingClassifier(random_state=1)

In [10]:
# # 先看看使用預設參數得到的結果，發現MSE為0.43
# reg.fit(x_train, y_train)
# y_pred = reg.predict(x_test)
# print(metrics.mean_squared_error(y_test, y_pred.astype(int)))

# 先看看使用預設參數得到的結果，發現accuracy_score為0.89
reg.fit(x_train, y_train)
y_pred = reg.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred.astype(int)))

0.89

In [11]:
# 設定要訓練的超參數組合
import itertools
n_estimators = [5, 10, 20, 30]
max_depth = [5, 10 ,15, 20]

# hp_combinations = list(itertools.product(n_estimators, max_depth))

param_grid = dict(n_estimators = n_estimators, max_depth = max_depth)
# for i in range(len(hp_combinations)):
#     param_grid = dict(n_estimators = hp_combinations[i][0], max_depth = hp_combinations[i][1])

    ## 建立搜尋物件，放入模型及參數組合字典 (n_jobs=-1 會使用全部 cpu 平行運算)
grid_search = GridSearchCV(reg, param_grid, scoring="neg_mean_squared_error", n_jobs=-1, verbose=1)

    # 開始搜尋最佳參數
grid_result = grid_search.fit(x_train, y_train)

    # 預設會跑 3-fold cross-validadtion，總共 9 種參數組合，總共要 train 27 次模型

Fitting 3 folds for each of 16 candidates, totalling 48 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  48 out of  48 | elapsed:    6.0s finished

In [12]:
# 印出最佳結果與最佳參數
print("Best Accuracy: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best Accuracy: -0.180000 using {'max_depth': 5, 'n_estimators': 30}

In [13]:
# 使用最佳參數重新建立模型
# reg_bestparam = GradientBoostingRegressor(max_depth=grid_result.best_params_['max_depth'],
#                                            n_estimators=grid_result.best_params_['n_estimators'])

reg_bestparam = GradientBoostingClassifier(max_depth=grid_result.best_params_['max_depth'],
                                           n_estimators=grid_result.best_params_['n_estimators'])

# 訓練模型
reg_bestparam.fit(x_train, y_train)

# 預測測試集
y_pred = reg_bestparam.predict(x_test)

In [14]:
print('GradientBoostingClassifier', accuracy_score(y_test, y_pred))

GradientBoostingClassifier 0.8833333333333333

In [15]:
reg = GradientBoostingClassifier(max_depth=5, n_estimators=20, random_state=1)
reg.fit(x_train, y_train)
y1_pred = reg.predict(test)
y1_pred

array([1, 0, 0, ..., 1, 0, 1])

In [16]:
Y1_pred = pd.DataFrame(y1_pred)

Y1_pred.index += 1

Y1_pred.columns = ['Solution']
Y1_pred['Id'] = np.arange(1,Y1_pred.shape[0]+1)
Y1_pred = Y1_pred[['Id', 'Solution']]

Y1_pred.to_csv(dir_data+'/kaggle_day048.csv', index=False)